### ISSUE TITLE
Configure colours

### ISSUE THREAD

**Issue by JoleneKearse** [JoleneKearse/weekend_rock_paper_scissors#1]
- [ ] Add base brand colours, where the background is a radial gradient: #131537 from #1F3757 at a starting point.
- [ ] Other background colours for action status: #3B4262, #203150, #263553, #2a3756 for a total of 4 values. #17213f is also there at darker in the computer choice area.  #172442 is darker still at the array of options (Step 1).  So 6 values so far.
- [ ] Possibly other values #f9f9f9 for score box.  #fff for title and subtitles.  #dddddd for rock paper scissors background.  #babfd4 for the inset box-shadow.  #3b4262 for the hand symbols themselves.  #161d3f for the rules button.
